AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Lambda01:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda01
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo01:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda02:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda02
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo02:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda03:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda03
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo03:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda04:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda04
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo04:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda05:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda05
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo05:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda06:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda06
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo06:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda07:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda07
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo07:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda08:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda08
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo08:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda09:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda09
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo09:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda10:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda10
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo10:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  LambaLab1Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "lab1Policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "lambda:*"
            Resource: "*"
          -
            Effect: "Allow"
            Action: "dynamodb:*"
            Resource: "*"
          -
            Effect: "Allow"
            Action:
              - iam:CreateAccessKey
              - iam:ListUsers
              - iam:ListAccessKeys
              - iam:PassRole
              - logs:describeLogGroups
              - logs:describeLogStreams
              - logs:getLogEvents
            Resource: "*"
          -
            Effect: "Deny"
            Action: "iam:*"
            Resource: "arn:aws:iam::057654311259:user/lfox"
          -
            Effect: "Deny"
            Action: "iam:*"
            Resource: "arn:aws:iam::057654311259:user/rvanderwerf"
          -
            Effect: "Deny"
            Action: "iam:*"
            Resource: "arn:aws:iam::057654311259:user/devopsAssistant"
          -
            Effect: "Deny"
            Action: "iam:*"
            Resource: "arn:aws:iam::057654311259:user/victoropsSkill"
      Users:
        - Ref: Lambda01
        - Ref: Lambda02
        - Ref: Lambda03
        - Ref: Lambda04
        - Ref: Lambda05
        - Ref: Lambda06
        - Ref: Lambda07
        - Ref: Lambda08
        - Ref: Lambda09
        - Ref: Lambda10