AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Lambda11:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda11
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo11:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"
      TableName:  Dynamo11
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda12:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda12
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo12:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"
      TableName:  Dynamo12
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda13:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda13
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo13:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"
      TableName:  Dynamo13
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda14:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda14
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo14:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"
      TableName:  Dynamo14
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda15:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda15
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo15:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"
      TableName:  Dynamo15
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda16:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda16
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo16:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"
      TableName:  Dynamo16
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda17:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda17
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo17:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"
      TableName:  Dynamo17
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda18:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda18
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo18:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"
      TableName:  Dynamo18
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda19:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda19
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo19:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"
      TableName:  Dynamo19
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  Lambda20:
    Type: AWS::IAM::User
    Properties:
      UserName:  Lambda20
      Path: "/"
      LoginProfile:
        Password: DrinkMoreBourbon1!

  Dynamo20:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"
      TableName:  Dynamo20
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  LambaLab2Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "lab1Policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "lambda:*"
            Resource: "*"
          -
            Effect: "Allow"
            Action: "dynamodb:*"
            Resource: "*"
          -
            Effect: "Allow"
            Action:
              - iam:CreateAccessKey
              - iam:ListUsers
              - iam:ListAccessKeys
              - iam:PassRole
              - logs:describeLogGroups
              - logs:describeLogStreams
              - logs:getLogEvents
              - dynamodb:*
            Resource: "*"
          -
            Effect: "Deny"
            Action: "iam:*"
            Resource: "arn:aws:iam::057654311259:user/lfox"
          -
            Effect: "Deny"
            Action: "iam:*"
            Resource: "arn:aws:iam::057654311259:user/rvanderwerf"
          -
            Effect: "Deny"
            Action: "iam:*"
            Resource: "arn:aws:iam::057654311259:user/devopsAssistant"
          -
            Effect: "Deny"
            Action: "iam:*"
            Resource: "arn:aws:iam::057654311259:user/victoropsSkill"
      Users:
        - Ref: Lambda11
        - Ref: Lambda12
        - Ref: Lambda13
        - Ref: Lambda14
        - Ref: Lambda15
        - Ref: Lambda16
        - Ref: Lambda17
        - Ref: Lambda18
        - Ref: Lambda19
        - Ref: Lambda20
